<?php

/**
 * Builds a WXR (WordPress eXtended RSS) XML string from the PHP array
 * produced by WXR_Parser, guaranteeing a lossless round-trip.
 */
class WXR_Builder {

	const PREAMBLE = <<<'XML'
<!--
 This is a WordPress eXtended RSS file generated by WordPress as an export of your site.
 It contains information about your site's posts, pages, comments, categories, and other content.
 You may use this file to transfer that content from one site to another.
 This file is not intended to serve as a complete backup of your site.

 To import this information into a WordPress site follow these steps:
 1. Log in to that site as an administrator.
 2. Go to Tools: Import in the WordPress admin panel.
 3. Install the "WordPress" importer from the list.
 4. Activate & Run Importer.
 5. Upload this file using the form provided on that page.
 6. You will first be asked to map the authors in this export file to users
    on the site. For each author, you may choose to map to an
    existing user on the site or to create a new user.
 7. WordPress will then import each of the posts, pages, comments, categories, etc.
    contained in this file into your site.
-->
XML;

	/**
	 * Build a WXR XML string from a parsed data array.
	 *
	 * @param array $data Array as returned by WXR_Parser::parse().
	 * @return string Valid WXR XML.
	 */
	public function build( array $data ): string {
		$meta    = $data['meta']    ?? [];
		$channel = $data['channel'] ?? [];
		$items   = $data['items']   ?? [];
		$ns      = $meta['namespaces'] ?? WXR_Parser::NAMESPACES;

		$ns_attrs = '';
		foreach ( $ns as $prefix => $uri ) {
			$ns_attrs .= " xmlns:{$prefix}=\"{$this->esc( $uri )}\"";
		}

		// Support both legacy 'generator' key and the normalized 'wordpress' key.
		if ( isset( $meta['wordpress'] ) ) {
			// YAML may parse '7.0' as float; use number_format to preserve decimal.
			$ver       = is_float( $meta['wordpress'] )
				? number_format( (float) $meta['wordpress'], 1 )
				: (string) $meta['wordpress'];
			$generator = 'WordPress/' . $ver;
		} else {
			$generator = $meta['generator'] ?? 'WordPress/latest';
		}
		$created = isset( $meta['created'] )
			? $this->expand_date( (string) $meta['created'] )
			: gmdate( 'Y-m-d H:i' );

		$out  = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
		$out .= self::PREAMBLE . "\n";
		$out .= "<!-- generator=\"{$generator}\" created=\"{$created}\" -->\n";
		$out .= "<rss version=\"2.0\"{$ns_attrs}>\n";
		$out .= "  <channel>\n";
		$out .= $this->t( 'title', $channel['title'] ?? '' );
		$out .= $this->t( 'link', $channel['link'] ?? '' );
		$out .= $this->t_empty( 'description', $channel['description'] ?? '' );
		$out .= $this->t( 'pubDate', $channel['pub_date'] ?? '' );
		$out .= $this->t( 'language', $channel['language'] ?? '' );
		$out .= $this->n( 'wp', 'wxr_version', $meta['wxr_version'] ?? '1.2' );
		// base_site_url / base_blog_url may be omitted in compact YAML; derive from link.
		$link = $channel['link'] ?? '';
		$out .= $this->n( 'wp', 'base_site_url', $channel['base_site_url'] ?? $link );
		$out .= $this->n( 'wp', 'base_blog_url', $channel['base_blog_url'] ?? $link );

		foreach ( $channel['authors'] ?? [] as $a ) {
			$out .= $this->build_author( $a );
		}

		$out .= $this->t( 'generator', $channel['generator'] ?? '' );

		if ( ! empty( $channel['image'] ) ) {
			$out .= $this->build_image( $channel['image'] );
		}

		foreach ( $channel['categories'] ?? [] as $term ) {
			$out .= $this->build_category( $term );
		}
		foreach ( $channel['tags'] ?? [] as $term ) {
			$out .= $this->build_tag( $term );
		}
		foreach ( $channel['terms'] ?? [] as $term ) {
			$out .= $this->build_term( $term );
		}

		foreach ( $items as $item ) {
			$out .= $this->build_item( $item );
		}

		$out .= "  </channel>\n";
		$out .= "</rss>\n";

		return $out;
	}

	// -------------------------------------------------------------------------
	// Primitive helpers
	// -------------------------------------------------------------------------

	private function esc( string $v ): string {
		return htmlspecialchars( $v, ENT_XML1 | ENT_COMPAT, 'UTF-8' );
	}

	/** Plain element. */
	private function t( string $tag, string $v ): string {
		return "<{$tag}>{$this->esc( $v )}</{$tag}>\n";
	}

	/** Element that renders as self-closing when empty. */
	private function t_empty( string $tag, string $v ): string {
		return $v === '' ? "<{$tag}/>\n" : "<{$tag}>{$this->esc( $v )}</{$tag}>\n";
	}

	/** CDATA element. */
	private function tc( string $tag, string $v ): string {
		return "<{$tag}><![CDATA[{$v}]]></{$tag}>\n";
	}

	/** Namespaced plain element. */
	private function n( string $ns, string $tag, string $v ): string {
		return "<{$ns}:{$tag}>{$this->esc( $v )}</{$ns}:{$tag}>\n";
	}

	/** Namespaced plain element — self-closing when empty. */
	private function n_empty( string $ns, string $tag, string $v ): string {
		return $v === '' ? "<{$ns}:{$tag}/>\n" : "<{$ns}:{$tag}>{$this->esc( $v )}</{$ns}:{$tag}>\n";
	}

	/** Namespaced CDATA element. */
	private function nc( string $ns, string $tag, string $v ): string {
		return "<{$ns}:{$tag}><![CDATA[{$v}]]></{$ns}:{$tag}>\n";
	}

	// -------------------------------------------------------------------------
	// Channel sub-elements
	// -------------------------------------------------------------------------

	private function build_author( array $a ): string {
		$out  = "<wp:author>\n";
		$out .= '  ' . $this->n( 'wp', 'author_id', (string) ( $a['id'] ?? 0 ) );
		$out .= '  ' . $this->n( 'wp', 'author_login', $a['login'] ?? '' );
		$out .= '  ' . $this->n( 'wp', 'author_email', $a['email'] ?? '' );
		$out .= '  ' . $this->nc( 'wp', 'author_display_name', $a['display_name'] ?? '' );
		$out .= '  ' . $this->nc( 'wp', 'author_first_name', $a['first_name'] ?? '' );
		$out .= '  ' . $this->nc( 'wp', 'author_last_name', $a['last_name'] ?? '' );
		$out .= "</wp:author>\n";
		return $out;
	}

	private function build_image( array $img ): string {
		$out  = "<image>\n";
		$out .= "\t" . $this->t( 'url', $img['url'] ?? '' );
		$out .= "\t" . $this->t( 'title', $img['title'] ?? '' );
		$out .= "\t" . $this->t( 'link', $img['link'] ?? '' );
		$out .= "\t" . $this->t( 'width', (string) ( $img['width'] ?? 0 ) );
		$out .= "\t" . $this->t( 'height', (string) ( $img['height'] ?? 0 ) );
		$out .= "</image> \n";
		return $out;
	}

	private function build_category( array $term ): string {
		$out  = "<wp:category>\n";
		$out .= '  ' . $this->n( 'wp', 'term_id', (string) ( $term['id'] ?? '' ) );
		$out .= '  ' . $this->nc( 'wp', 'category_nicename', $term['slug'] ?? '' );
		$out .= '  ' . $this->nc( 'wp', 'category_parent', $term['parent'] ?? '' );
		$out .= '  ' . $this->nc( 'wp', 'cat_name', $term['name'] ?? '' );
		if ( isset( $term['description'] ) ) {
			$out .= '  ' . $this->nc( 'wp', 'category_description', $term['description'] );
		}
		$out .= "</wp:category>\n";
		return $out;
	}

	private function build_tag( array $term ): string {
		$out  = "<wp:tag>\n";
		$out .= '  ' . $this->n( 'wp', 'term_id', (string) ( $term['id'] ?? '' ) );
		$out .= '  ' . $this->nc( 'wp', 'tag_slug', $term['slug'] ?? '' );
		$out .= '  ' . $this->nc( 'wp', 'tag_name', $term['name'] ?? '' );
		if ( isset( $term['description'] ) ) {
			$out .= '  ' . $this->nc( 'wp', 'tag_description', $term['description'] );
		}
		$out .= "</wp:tag>\n";
		return $out;
	}

	private function build_term( array $term ): string {
		$out  = "<wp:term>\n";
		$out .= '  ' . $this->n( 'wp', 'term_id', (string) ( $term['id'] ?? '' ) );
		$out .= '  ' . $this->n( 'wp', 'term_taxonomy', $term['taxonomy'] ?? '' );
		$out .= '  ' . $this->nc( 'wp', 'term_slug', $term['slug'] ?? '' );
		$out .= '  ' . $this->nc( 'wp', 'term_parent', $term['parent'] ?? '' );
		$out .= '  ' . $this->nc( 'wp', 'term_name', $term['name'] ?? '' );
		if ( isset( $term['description'] ) ) {
			$out .= '  ' . $this->nc( 'wp', 'term_description', $term['description'] );
		}
		$out .= "</wp:term>\n";
		return $out;
	}

	// -------------------------------------------------------------------------
	// Items
	// -------------------------------------------------------------------------

	private function build_item( array $item ): string {
		$guid = $item['guid'] ?? [ 'value' => '', 'isPermaLink' => 'false' ];

		// Single post_date field with optional TZ offset derives local+gmt pair.
		[ $post_date, $post_date_gmt ] = $this->parse_date_pair( $item['post_date'] ?? '' );

		// post_modified only when explicitly set; otherwise mirrors post_date.
		[ $post_modified, $post_modified_gmt ] = isset( $item['post_modified'] )
			? $this->parse_date_pair( $item['post_modified'] )
			: [ $post_date, $post_date_gmt ];

		// Restore compact-omitted pub_date from post_date (RFC 822).
		$raw_pub = $this->expand_date( $item['pub_date'] ?? '' );
		if ( '' === $raw_pub && '' !== $post_date ) {
			$ts      = strtotime( $post_date_gmt ?: $post_date );
			$raw_pub = $ts ? gmdate( 'D, d M Y H:i:s +0000', $ts ) : '';
		}
		$pub_date = $raw_pub;

		$out  = "<item>\n";
		$out .= '  ' . $this->tc( 'title', $item['title'] ?? '' );
		$out .= '  ' . $this->t( 'link', $item['link'] ?? '' );
		$out .= '  ' . $this->t( 'pubDate', $pub_date );
		$out .= '  <dc:creator>' . $this->esc( $item['creator'] ?? '' ) . "</dc:creator>\n";
		$out .= '  <guid isPermaLink="' . $this->esc( $guid['isPermaLink'] ) . '">'
			. $this->esc( $guid['value'] ) . "</guid>\n";
		$out .= '  ' . $this->t_empty( 'description', $item['description'] ?? '' );
		$out .= '  <content:encoded><![CDATA[' . ( $item['content'] ?? '' ) . "]]></content:encoded>\n";
		$out .= '  <excerpt:encoded><![CDATA[' . ( $item['excerpt'] ?? '' ) . "]]></excerpt:encoded>\n";
		$out .= '  ' . $this->n( 'wp', 'post_id', (string) ( $item['post_id'] ?? 0 ) );
		$out .= '  ' . $this->n( 'wp', 'post_date', $post_date );
		$out .= '  ' . $this->n( 'wp', 'post_date_gmt', $post_date_gmt );
		$out .= '  ' . $this->n( 'wp', 'post_modified', $post_modified );
		$out .= '  ' . $this->n( 'wp', 'post_modified_gmt', $post_modified_gmt );
		$out .= '  ' . $this->n( 'wp', 'comment_status', $item['comment_status'] ?? 'closed' );
		$out .= '  ' . $this->n( 'wp', 'ping_status', $item['ping_status'] ?? 'closed' );
		$out .= '  ' . $this->n( 'wp', 'post_name', $item['post_name'] ?? '' );
		$out .= '  ' . $this->n( 'wp', 'status', $item['status'] ?? 'publish' );
		$out .= '  ' . $this->n( 'wp', 'post_parent', (string) ( $item['post_parent'] ?? 0 ) );
		$out .= '  ' . $this->n( 'wp', 'menu_order', (string) ( $item['menu_order'] ?? 0 ) );
		$out .= '  ' . $this->n( 'wp', 'post_type', $item['post_type'] ?? '' );
		$out .= '  ' . $this->n_empty( 'wp', 'post_password', $item['post_password'] ?? '' );
		$out .= '  ' . $this->n( 'wp', 'is_sticky', (string) ( $item['is_sticky'] ?? 0 ) );

		if ( ! empty( $item['attachment_url'] ) ) {
			$out .= '  ' . $this->n( 'wp', 'attachment_url', $item['attachment_url'] );
		}

		foreach ( $item['categories'] ?? [] as $cat ) {
			$domain   = $this->esc( $cat['domain'] ?? '' );
			$nicename = $this->esc( $cat['nicename'] ?? '' );
			$out .= "  <category domain=\"{$domain}\" nicename=\"{$nicename}\">"
				. '<![CDATA[' . ( $cat['value'] ?? '' ) . "]]></category>\n";
		}

		foreach ( $item['meta'] ?? [] as $key => $value ) {
			$out .= "  <wp:postmeta>\n";
			$out .= '    ' . $this->nc( 'wp', 'meta_key', (string) $key );
			$out .= '    ' . $this->nc( 'wp', 'meta_value', (string) $value );
			$out .= "  </wp:postmeta>\n";
		}

		foreach ( $item['comments'] ?? [] as $comment ) {
			$out .= $this->build_comment( $comment );
		}

		$out .= "</item>\n";
		return $out;
	}

	/**
	 * Parse a compact date string into a [local, gmt] pair.
	 *
	 * Format: "YYYYMMDDTHHmmss[±HHMM]"
	 *   - No suffix or offset=0 → local === gmt (UTC).
	 *   - Non-zero offset       → local is bare datetime, gmt is computed UTC.
	 *
	 * @return array{0: string, 1: string}  [local "YYYY-MM-DD HH:MM:SS", gmt "YYYY-MM-DD HH:MM:SS"]
	 */
	private function parse_date_pair( string $v ): array {
		if ( '' === $v ) {
			return [ '', '' ];
		}
		// ISO 8601 basic with optional TZ: YYYYMMDDTHHmmss[±HHMM]
		if ( preg_match( '/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})([+-](\d{2})(\d{2})?)?$/', $v, $m ) ) {
			$local = "{$m[1]}-{$m[2]}-{$m[3]} {$m[4]}:{$m[5]}:{$m[6]}";
			if ( empty( $m[7] ) ) {
				// No TZ suffix → treat as UTC; local === gmt.
				return [ $local, $local ];
			}
			$sign       = $m[7][0] === '+' ? 1 : -1;
			$offset_sec = $sign * ( (int) $m[8] * 3600 + (int) ( $m[9] ?? 0 ) * 60 );
			if ( 0 === $offset_sec ) {
				// Explicit +0000 → still UTC.
				return [ $local, $local ];
			}
			// Compute UTC by subtracting the local offset.
			$ts  = mktime( (int) $m[4], (int) $m[5], (int) $m[6], (int) $m[2], (int) $m[3], (int) $m[1] );
			$gmt = gmdate( 'Y-m-d H:i:s', $ts - $offset_sec );
			return [ $local, $gmt ];
		}
		// No TZ-aware form — fall back to expand_date for legacy / already-expanded values.
		$expanded = $this->expand_date( $v );
		return [ $expanded, $expanded ];
	}

	/**
	 * Expand a compact datetime back to "YYYY-MM-DD HH:MM:SS" (WXR field format).
	 *
	 * Recognised compact forms:
	 *   ISO 8601 basic "YYYYMMDDTHHmmss[±TZ]"  — TZ stripped (use parse_date_pair for TZ handling)
	 *   ISO 8601 basic "YYYYMMDDT HHMM"         — created field (no seconds)
	 *   14 pure digits YYYYMMDDHHmmss            — legacy integer-string
	 *   12 pure digits YYYYMMDDHHMM              — legacy integer-string
	 * RFC-822, already-expanded, and unrecognised values pass through unchanged.
	 */
	private function expand_date( string $v ): string {
		// ISO 8601 basic: "YYYYMMDDTHHmmss" or "YYYYMMDDTHHmmss±HH[MM]".
		if ( preg_match( '/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})(?:[+-]\d{2,4})?$/', $v, $m ) ) {
			return "{$m[1]}-{$m[2]}-{$m[3]} {$m[4]}:{$m[5]}:{$m[6]}";
		}
		// Created field: "YYYYMMDDT HHMM" (no seconds).
		if ( preg_match( '/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})$/', $v, $m ) ) {
			return "{$m[1]}-{$m[2]}-{$m[3]} {$m[4]}:{$m[5]}:00";
		}
		// Legacy: 14 pure digits YYYYMMDDHHmmss.
		if ( preg_match( '/^\d{14}$/', $v ) ) {
			$d = \DateTime::createFromFormat( 'YmdHis', $v, new \DateTimeZone( 'UTC' ) );
			return $d ? $d->format( 'Y-m-d H:i:s' ) : $v;
		}
		// Legacy: 12 pure digits YYYYMMDDHHMM.
		if ( preg_match( '/^\d{12}$/', $v ) ) {
			$d = \DateTime::createFromFormat( 'YmdHi', $v, new \DateTimeZone( 'UTC' ) );
			return $d ? $d->format( 'Y-m-d H:i:s' ) : $v;
		}
		return $v; // RFC-822, already expanded, or unrecognised — pass through.
	}

	private function build_comment( array $c ): string {
		$out  = "<wp:comment>\n";
		$out .= '  ' . $this->n( 'wp', 'comment_id', (string) ( $c['id'] ?? 0 ) );
		$out .= '  ' . $this->nc( 'wp', 'comment_author', $c['author'] ?? '' );
		$out .= '  ' . $this->n( 'wp', 'comment_author_email', $c['author_email'] ?? '' );
		$out .= '  ' . $this->n( 'wp', 'comment_author_url', $c['author_url'] ?? '' );
		$out .= '  ' . $this->n( 'wp', 'comment_author_IP', $c['author_ip'] ?? '' );
		$out .= '  ' . $this->n( 'wp', 'comment_date', $c['date'] ?? '' );
		$out .= '  ' . $this->n( 'wp', 'comment_date_gmt', $c['date_gmt'] ?? '' );
		$out .= '  ' . $this->nc( 'wp', 'comment_content', $c['content'] ?? '' );
		$out .= '  ' . $this->n( 'wp', 'comment_approved', $c['approved'] ?? '1' );
		$out .= '  ' . $this->n( 'wp', 'comment_type', $c['type'] ?? '' );
		$out .= '  ' . $this->n( 'wp', 'comment_parent', (string) ( $c['parent'] ?? 0 ) );
		$out .= '  ' . $this->n( 'wp', 'comment_user_id', (string) ( $c['user_id'] ?? 0 ) );
		$out .= "</wp:comment>\n";
		return $out;
	}
}
